WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GREEN_BLUE = (0, 153, 153)
LIGHT_GRAY = (192, 192, 192)
RED = (255, 0, 0)

BLOCK_SIZE = 50
LEFT_MARGIN = 5 * BLOCK_SIZE
UPPER_MARGIN = 2 * BLOCK_SIZE
# 30 = 2x10 blocks width in two grids + hard-coded 5*blocks gap after each grid!
SIZE = (LEFT_MARGIN + 30 * BLOCK_SIZE, UPPER_MARGIN + 15 * BLOCK_SIZE)
LETTERS = "ABCDEFGHIJ"

# This ratio is purely for scaling the font according to the block size
FONT_SIZE = int(BLOCK_SIZE / 1.5)
GAME_OVER_FONT_SIZE = 3 * BLOCK_SIZE
LINE_WIDTH = 1

AUTO_BUTTON_PLACE = LEFT_MARGIN + 17 * BLOCK_SIZE
MANUAL_BUTTON_PLACE = LEFT_MARGIN + 20 * BLOCK_SIZE
HOW_TO_CREATE_SHIPS_MESSAGE = "How do you want to create your ships? Click the button"

UNDO_MESSAGE = "To undo the last ship click the button"
UNDO_BUTTON_PLACE = LEFT_MARGIN + 12 * BLOCK_SIZE

PLAY_AGAIN_MESSAGE = "Do you want to play again or quit?"
PLAY_AGAIN_BUTTON_PLACE = LEFT_MARGIN + 15 * BLOCK_SIZE

RECT_FOR_GRIDS = (0, 0, SIZE[0], UPPER_MARGIN + 12 * BLOCK_SIZE)
RECT_FOR_MESSAGES_AND_BUTTONS = (0, UPPER_MARGIN + 11 * BLOCK_SIZE, SIZE[0], 5 * BLOCK_SIZE)
MESSAGE_RECT_COMPUTER = (
    LEFT_MARGIN - 2 * BLOCK_SIZE,
    UPPER_MARGIN + 11 * BLOCK_SIZE,
    14 * BLOCK_SIZE,
    4 * BLOCK_SIZE,
)
MESSAGE_RECT_HUMAN = (
    LEFT_MARGIN + 15 * BLOCK_SIZE,
    UPPER_MARGIN + 11 * BLOCK_SIZE,
    10 * BLOCK_SIZE,
    4 * BLOCK_SIZE,
)
